dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk11
script: mvn verify -Pquality,linux
cache:
  directories:
  - "~/.m2/repository"
deploy:
- provider: script
  script: chmod +x travis/deploy.sh && travis/deploy.sh
  skip_cleanup: true
  on:
    branch: multiple-jdks
    jdk: openjdk8
- provider: script
  script: chmod +x travis/deploy.sh && travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
- provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: "./distribution/target/styx-*.zip"
  skip_cleanup: true
  on:
    tags: true