/*
  Copyright (C) 2013-2021 Expedia Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 */
package com.hotels.styx.server;

import com.hotels.styx.api.metrics.MeterFactory;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Tags;
import io.micrometer.core.instrument.Timer;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import static com.hotels.styx.api.Metrics.name;
import static java.lang.String.valueOf;

/**
 * An implementation of request event sink that maintains Styx request statistics.
 */
public class RequestStatsCollector implements RequestProgressListener {

    public static final String STATUS_TAG = "statusCode";
    public static final String STATUS_CLASS_TAG = "statusClass";

    public static final String REQUEST_OUTSTANDING = "request.outstanding";
    public static final String REQUEST_LATENCY = "request.latency";
    public static final String REQUEST_RECEIVED = "request.received";
    public static final String RESPONSE_SENT = "response.sent";
    public static final String RESPONSE_STATUS = "response.status";

    public static final String STATUS_CLASS_UNRECOGNISED = "unrecognised";

    private final MeterRegistry registry;
    private final String prefix;

    private final Timer latencyTimer;
    private final Counter requestsIncoming;

    private final Counter responsesSent;

    private final ConcurrentHashMap<Object, Timer.Sample> ongoingRequests = new ConcurrentHashMap<>();

    /**
     * Constructs a collector with a {@link MeterRegistry} to report stastistics to.
     *
     * @param registry a registry to report to
     * @param prefix a name prefix for all metrics generated by this collector
     */
    public RequestStatsCollector(MeterRegistry registry, String prefix) {
        this.registry = registry;
        this.prefix = prefix;

        registry.gauge(name(prefix, REQUEST_OUTSTANDING), ongoingRequests, Map::size);
        this.latencyTimer = MeterFactory.timer(registry, name(prefix, REQUEST_LATENCY));

        this.requestsIncoming = registry.counter(name(prefix, REQUEST_RECEIVED));
        this.responsesSent = registry.counter(name(prefix, RESPONSE_SENT));
    }

    @Override
    public void onRequest(Object requestId) {
        Timer.Sample previous = this.ongoingRequests.putIfAbsent(requestId, Timer.start(registry));
        if (previous == null) {
            this.requestsIncoming.increment();
        }
    }

    @Override
    public void onComplete(Object requestId, int responseStatus) {
        Timer.Sample startTime = this.ongoingRequests.remove(requestId);
        if (startTime != null) {
            updateResponseStatusCounter(responseStatus);
            this.responsesSent.increment();

            startTime.stop(latencyTimer);
        }
    }

    @Override
    public void onTerminate(Object requestId) {
        Timer.Sample startTime = this.ongoingRequests.remove(requestId);
        if (startTime != null) {
            startTime.stop(latencyTimer);
        }
    }

    private void updateResponseStatusCounter(int code) {
        Tags statusTags;
        if (code >= 100 && code < 600) {
            statusTags = Tags.of(STATUS_CLASS_TAG, code / 100 + "xx")
                    .and(STATUS_TAG, valueOf(code));
        } else {
            statusTags = Tags.of(STATUS_CLASS_TAG, STATUS_CLASS_UNRECOGNISED)
                    .and(STATUS_TAG, STATUS_CLASS_UNRECOGNISED);
        }

        registry.counter(name(prefix, RESPONSE_STATUS), statusTags).increment();
    }
}
