---

jvmRouteName: "${jvm.route:noJvmRouteSet}"

proxy:
  connectors:
    http:
      port: 8080
    https:
      port: 8443
      sslProvider: OPENSSL # Also supports JDK
      certificateFile: ${STYX_HOME:classpath:}/conf/tls/testCredentials.crt
      certificateKeyFile: ${STYX_HOME:classpath:}/conf/tls/testCredentials.key
      sessionTimeoutMillis: 300000
      sessionCacheSize: 20000
  bossThreadsCount: 1
  clientWorkerThreadsCount: 0
  workerThreadsCount: 0
  maxInitialLength: 4096
  maxHeaderSize: 8192
  maxChunkSize: 8192
  requestTimeoutMillis: 12000
  keepAliveTimeoutMillis: 12000
  maxConnectionsCount: 4096

admin:
  connectors:
    http:
      port: 9000
  bossThreadsCount: 1
  workerThreadsCount: 1
  maxInitialLength: 4096
  maxHeaderSize: 8192
  maxChunkSize: 8192
  metricsCache:
    enabled: true
    expirationMillis: 10000

routingObjects:
  h2Handler:
    type: StaticResponseHandler
    config:

servers:
  h1Server:
    type: HttpServer
    config:
      port: 8080
      listener: h1Handler

      tlsSettings:
        sslProvider: OPENSSL # Also supports JDK
        certificateFile: ${STYX_HOME:classpath:}/conf/tls/testCredentials.crt
        certificateKeyFile: ${STYX_HOME:classpath:}/conf/tls/testCredentials.key
        sessionTimeoutMillis: 300000
        sessionCacheSize: 20000

      maxInitialLength: 4096
      maxHeaderSize: 8192
      maxChunkSize: 8192

      requestTimeoutMillis: 12000
      keepAliveTimeoutMillis: 12000
      maxConnectionsCount: 4096

      bossThreadsCount: 1
      workerThreadsCount: 0

  h2Server:
    type: Http2Server
    config:
      port: 8443
      listener: h2Handler

      maxInitialLength: 4096
      maxHeaderSize: 8192
      maxChunkSize: 8192

      requestTimeoutMillis: 12000
      keepAliveTimeoutMillis: 12000
      maxConnectionsCount: 4096

      bossThreadsCount: 1
      workerThreadsCount: 0

  admin:
    type: HttpServer
    config:
      port: 9000
      listener: adminHandler
